import { afterEach, test } from 'node:test'
import assert from 'node:assert/strict'
import { createTopicCheck } from '../src/utils/topicCheckLogic.js'
import { createInitialTopicCheck, createTopicCheckKey, loadTopicCheck, saveTopicCheck } from '../src/utils/topicCheckStore.js'
const storage=new Map(); global.window={localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)}}; afterEach(()=>storage.clear())
function library(count=11){return Object.fromEntries(Array.from({length:count},(_,i)=>{const n=i+1,id=`p${String(n).padStart(2,'0')}`;return [id,{packageId:id,packageNumber:n,packageTitle:`Thema ${n}`,questions:Array.from({length:4},(_,j)=>({questionId:`${id}-${j}`,questionType:['mc','yesNo','freeText','mc'][j],question:'synthetisch'}))}]}))}
function rnd(values){let i=0;return()=>values[i++%values.length]}
for(const size of [1,2,3]) test(`Themencheck: ${size} Frage(n) je Paket und komplette Coverage`,()=>{const l=library();const c=createTopicCheck(l,size,rnd([.2,.8,.4]));assert.equal(c.orderedQuestionRefs.length,11*size);assert.equal(new Set(c.orderedQuestionRefs.map(r=>r.packageId)).size,11);assert.equal(new Set(c.orderedQuestionRefs.map(r=>`${r.packageId}:${r.questionId}`)).size,11*size)})
test('Themencheck: Teilmenge mit fünf Paketen liefert 5/10/15 ohne Duplikate',()=>{for(const size of [1,2,3])assert.equal(createTopicCheck(library(5),size,()=>.3).orderedQuestionRefs.length,5*size)})
test('Themencheck: paketübergreifende Reihenfolge und Fragetypen werden gemischt',()=>{const l=library(5);const c=createTopicCheck(l,3,rnd([.1,.7,.4,.9]));assert.ok(c.orderedQuestionRefs.slice(1).some((r,i)=>r.packageId!==c.orderedQuestionRefs[i].packageId));const types=c.orderedQuestionRefs.map(r=>l[r.packageId].questions.find(q=>q.questionId===r.questionId).questionType);assert.equal(new Set(types).size,3)})
test('Themencheck: Resume bewahrt identische Referenzen, Statistik und keine Fragenobjekte',()=>{const l=library(3),round=createTopicCheck(l,2,()=>.4),session={...createInitialTopicCheck(l),...round,currentQuestionIndex:2,answers:{'p01::p01-0':{questionType:'mc',selectedAnswer:'A',correct:true}},statistics:{correct:1,wrong:0,green:0,yellow:0,red:0}};saveTopicCheck(l,session);const loaded=loadTopicCheck(l);assert.deepEqual(loaded.orderedQuestionRefs,round.orderedQuestionRefs);assert.equal(loaded.statistics.correct,1);const raw=storage.get(createTopicCheckKey(l));assert.equal(raw.includes('synthetisch'),false);assert.equal(raw.includes('questions'),false)})
test('Themencheck: Neustart mit neuer Zufallsfolge erzeugt andere Session und bleibt vom Paketstore getrennt',()=>{const l=library(4);assert.notDeepEqual(createTopicCheck(l,2,()=>.01).orderedQuestionRefs,createTopicCheck(l,2,()=>.99).orderedQuestionRefs);storage.set('pwl-quiz-package-progress:v1:p01:x','untouched');saveTopicCheck(l,{...createInitialTopicCheck(l),...createTopicCheck(l,1)});assert.equal(storage.get('pwl-quiz-package-progress:v1:p01:x'),'untouched')})
