<script setup>
import { computed, onBeforeUnmount, reactive, ref } from 'vue'
import QuizCard from './QuizCard.vue'
import YesNoCard from './YesNoCard.vue'
import FreeTextCard from './FreeTextCard.vue'
import { createTopicCheck } from '../utils/topicCheckLogic.js'
import { recordMistake } from '../utils/mistakeStore.js'
import { clearTopicCheck, createInitialTopicCheck, loadTopicCheck, saveTopicCheck } from '../utils/topicCheckStore.js'
const props = defineProps({ packageBanksById: { type: Object, required: true } })
const session = reactive(createInitialTopicCheck(props.packageBanksById)); const setupOpen = ref(true); const resumeOpen = ref(false); const selected = ref(null); const answered = ref(false)
const banks = computed(() => Object.values(props.packageBanksById).sort((a,b) => a.packageNumber-b.packageNumber)); const hasBanks = computed(() => banks.value.length > 0); const missing = computed(() => Array.from({length:11},(_,i)=>`p${String(i+1).padStart(2,'0')}`).filter(id=>!props.packageBanksById[id]))
const byRef = computed(() => new Map(banks.value.flatMap(bank => bank.questions.map(question => [`${bank.packageId}::${question.questionId}`, { bank, question }]))))
const current = computed(() => byRef.value.get(`${session.orderedQuestionRefs[session.currentQuestionIndex]?.packageId}::${session.orderedQuestionRefs[session.currentQuestionIndex]?.questionId}`)); const total = computed(()=>session.orderedQuestionRefs.length); const last = computed(()=>session.currentQuestionIndex===total.value-1)
const reached = computed(()=>new Set(Object.keys(session.answers).map(key=>key.split('::')[0]))); const currentAnswer = computed(()=>current.value ? session.answers[`${current.value.bank.packageId}::${current.value.question.questionId}`] : null)
function save(){ saveTopicCheck(props.packageBanksById, session) }
function start(size){ if(!hasBanks.value)return; Object.assign(session, createInitialTopicCheck(props.packageBanksById), createTopicCheck(props.packageBanksById,size)); setupOpen.value=false; resumeOpen.value=false; selected.value=null; answered.value=false; save() }
function offerResume(){ if(!hasBanks.value){setupOpen.value=true;resumeOpen.value=false;return} const stored=loadTopicCheck(props.packageBanksById); if(stored.orderedQuestionRefs.length&&stored.sessionStatus==='inProgress'){ Object.assign(session,stored); resumeOpen.value=true } else setupOpen.value=true }
function resume(){ setupOpen.value=false; resumeOpen.value=false; const a=currentAnswer.value; selected.value=a?.selectedAnswer ?? null; answered.value=Boolean(a && a.questionType!=='freeText') }
function objective(value){ if(answered.value)return; selected.value=value; answered.value=true; const correct=value===current.value.question.correctAnswer; session.answers[`${current.value.bank.packageId}::${current.value.question.questionId}`]={questionType:current.value.question.questionType,selectedAnswer:value,correct}; session.statistics[correct?'correct':'wrong']++; recordMistake({packageId:current.value.bank.packageId,questionId:current.value.question.questionId,questionType:current.value.question.questionType,result:correct}); save() }
function free(e){ const key=`${current.value.bank.packageId}::${current.value.question.questionId}`; const old=session.answers[key]; if(old?.status) session.statistics[old.status]--; session.statistics[e.rating]++; session.answers[key]={questionType:'freeText',userAnswer:e.userAnswer,status:e.rating}; recordMistake({packageId:current.value.bank.packageId,questionId:current.value.question.questionId,questionType:'freeText',result:e.rating}); save() }
function next(){ if(!last.value)session.currentQuestionIndex++; selected.value=null; answered.value=false; save() }
function finish(){session.sessionStatus='completed';save()}
function restart(){clearTopicCheck(props.packageBanksById);Object.assign(session,createInitialTopicCheck(props.packageBanksById));setupOpen.value=true;resumeOpen.value=false}
offerResume(); onBeforeUnmount(save)
</script>
<template>
<section class="package-mode-layout topic-check">
  <section v-if="setupOpen && !hasBanks" class="result-card package-bank-empty-state" role="status"><p class="eyebrow">Paketbanken erforderlich</p><h2>Keine Paketbanken geladen.</h2><p>Bitte lade zuerst deine private Lernbibliothek.</p><p class="package-library-count">0 von 11 Paketbanken geladen</p></section>
  <section v-else-if="setupOpen" class="result-card"><p class="eyebrow">Themengebiet-Check</p><h2>{{ banks.length }} von 11 Themengebieten verfügbar</h2><p v-if="missing.length">Fehlend: {{ missing.join(', ') }}. Der Check verwendet nur geladene Themengebiete.</p><p v-else>Alle Themengebiete sind verfügbar.</p><div v-if="resumeOpen" class="result-actions"><button class="primary-button" @click="resume">Letzten Themencheck fortsetzen</button><button class="secondary-button" @click="resumeOpen=false">Neuen Themencheck starten</button></div><div v-else class="result-actions"><button class="primary-button" @click="start(1)">Kurzcheck · 1 Frage je Gebiet</button><button class="secondary-button" @click="start(2)">Intensivcheck · 2 Fragen je Gebiet</button><button class="secondary-button" @click="start(3)">Komplettcheck · 3 Fragen je Gebiet</button></div></section>
  <section v-else-if="!session.sessionStatus || session.sessionStatus==='inProgress'" class="quiz-layout"><aside class="score-card progress-card"><h2>Themengebiet-Check</h2><p>Frage {{ session.currentQuestionIndex+1 }} von {{ total }}</p><p>Themengebiete erreicht: {{ reached.size }} von {{ banks.length }}</p><button class="secondary-button" @click="restart">Neuen Check starten</button></aside><template v-if="current"><p class="topic-label">Themengebiet {{ current.bank.packageNumber }}/11 – {{ current.bank.packageTitle }}</p><QuizCard v-if="current.question.questionType==='mc'" :key="current.question.questionId" :question="{...current.question,category:current.bank.packageTitle}" :selected-answer="selected" :is-answered="answered" :is-last-question="last" @select-answer="objective" @next-question="next" @restart-quiz="finish"/><YesNoCard v-else-if="current.question.questionType==='yesNo'" :key="current.question.questionId" :question="current.question" :selected-answer="selected" :is-answered="answered" :is-last-question="last" @select-answer="objective" @next-question="next" @finish="finish"/><FreeTextCard v-else :key="current.question.questionId" :question="{...current.question,category:current.bank.packageTitle}" :is-last-question="last" :initial-answer="currentAnswer?.userAnswer||''" :initial-status="currentAnswer?.status||null" :show-model-answer-toggle="true" @evaluated="free" @next-question="next" @restart-training="finish"/></template></section>
  <section v-else class="result-card"><p class="eyebrow">Themengebiet-Check abgeschlossen</p><h2>{{ reached.size }} von {{ banks.length }} Themengebieten geprüft</h2><div class="result-grid"><div><span>Bearbeitet</span><strong>{{ Object.keys(session.answers).length }}</strong></div><div><span>Korrekt</span><strong>{{ session.statistics.correct }}</strong></div><div><span>Falsch</span><strong>{{ session.statistics.wrong }}</strong></div><div><span>Freitext Grün</span><strong>{{ session.statistics.green }}</strong></div><div><span>Freitext Gelb</span><strong>{{ session.statistics.yellow }}</strong></div><div><span>Freitext Rot</span><strong>{{ session.statistics.red }}</strong></div></div><p class="topic-check-list"><span v-for="bank in banks" :key="bank.packageId">{{ bank.packageId }} {{ reached.has(bank.packageId)?'✓':'–' }}</span></p><button class="primary-button" @click="restart">Neuen Themencheck starten</button></section>
</section>
</template>
